spring.application.name=EMT-Labs
server.port=9090

spring.datasource.url=jdbc:postgresql://localhost:5432/emt_book
spring.datasource.username=emt
spring.datasource.password=emt

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=false
spring.sql.init.mode=never
spring.profiles.active=dev


